# Generated by Django 4.2.7 on 2025-04-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20250411_1802"),
        ("api", "0003_auto_20250411_1803"),
    ]

    operations = []
