# Generated by Django 5.1.5 on 2025-03-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_discussionpostupvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="discussion",
            name="total_posts",
        ),
        migrations.RemoveField(
            model_name="discussion",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="discussion",
            name="description",
            field=models.TextField(default="description"),
        ),
        migrations.AddField(
            model_name="discussion",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discussions",
                to="api.category",
            ),
        ),
    ]
