# Generated by Django 4.2.7 on 2025-04-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customuser_is_active"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillprofile",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_profiles",
                to="api.category",
            ),
        ),
    ]
