# Generated by Django 4.2.7 on 2025-04-24 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customuser_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0002_skillprofile_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skillprofile",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="skillprofile",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skill_profiles",
                to="api.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillprofile",
            unique_together={("user", "skill", "category")},
        ),
    ]
