# Generated by Django 4.2.7 on 2025-04-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customuser_is_active"),
        ("skills", "0003_alter_skillprofile_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillprofile",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skill_profiles",
                to="api.category",
            ),
        ),
    ]
