# Generated by Django 4.2.7 on 2025-04-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_alter_skillprofile_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
