# Generated by Django 4.2.7 on 2025-04-28 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0005_alter_mentorship_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorship",
            name="chat_session_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mentorship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="mentorship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="mentorship",
            index=models.Index(
                fields=["learner", "status"], name="skills_ment_learner_081746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorship",
            index=models.Index(
                fields=["mentor", "status"], name="skills_ment_mentor__9c763c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorship",
            constraint=models.UniqueConstraint(
                fields=("learner", "mentor", "skill"), name="unique_mentorship"
            ),
        ),
    ]
