# Generated by Django 5.1.5 on 2025-03-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helprequest",
            name="project_details",
        ),
    ]
