# Generated by Django 5.1.5 on 2025-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_videocall"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
    ]
