# Generated by Django 4.2.7 on 2025-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                max_length=50,
            ),
        ),
    ]
