# Generated by Django 4.2.7 on 2025-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="info", max_length=50),
        ),
    ]
