# Generated by Django 4.2.7 on 2025-04-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("projects", "0009_chatmessage_mentorship_chat_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocall",
            name="mentorship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_calls",
                to="skills.mentorship",
            ),
        ),
        migrations.AlterField(
            model_name="videocall",
            name="help_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_calls",
                to="projects.helprequest",
            ),
        ),
    ]
