# Generated by Django 4.2.7 on 2025-04-28 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_videocall_mentorship_alter_videocall_help_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="mentorship_chat_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="helpcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("resolved", "Resolved")],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(db_index=True, default="info", max_length=50),
        ),
        migrations.AlterField(
            model_name="videocall",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_session", "timestamp"],
                name="projects_ch_chat_se_48e5db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["requester", "is_active"], name="projects_ch_request_628fff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["helper", "is_active"], name="projects_ch_helper__afad5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpcomment",
            index=models.Index(
                fields=["help_request", "created_at"],
                name="projects_he_help_re_aa92ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(
                fields=["created_by", "status"], name="projects_he_created_0302f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="projects_no_user_id_f3b457_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videocall",
            index=models.Index(
                fields=["requester", "is_active"], name="projects_vi_request_394901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videocall",
            index=models.Index(
                fields=["helper", "is_active"], name="projects_vi_helper__55b23c_idx"
            ),
        ),
    ]
