# Generated by Django 4.2.7 on 2025-04-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_resourcevote_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="file",
        ),
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resources/")),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="resources.resource",
                    ),
                ),
            ],
        ),
    ]
