# Generated by Django 4.2.7 on 2025-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_remove_resource_file_resourcefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="resources_r_uploade_7ce202_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["category", "created_at"], name="resources_r_categor_04ca8b_idx"
            ),
        ),
    ]
